myVar = 5 + 10; // assigned 15
var quotes = [
'We are what we think. `I never said that!` – the Buddha',
'What we achieve inwardly will change outer reality. – Plutarch',
'If your dreams don’t scare you, they aren’t big enough. – Muhammad Ali',
// 'Complaining is a sign that someone isn´t willing to risk moving on a changeable situation, or won´t consider the immutable circumstance in his or her plans. This is a temporary and hollow form of self-validation. // When you start to make things happen, you really begin to believe you can make things happen. And that makes things happen. – David Allen',
// 'Había empezado a escribir para fijar los “secretos” que hubiera podido olvidar. Y más que para fijarlos, para suscitarlos, para provocar secretos que debieran escribirse. Todavía creo que pensamos a partir de lo que escribimos y no al revés. – Louis Aragon',
// 'Fundamentally, a society that asks questions and has the power to answer them is a healthier society than one that simply accepts what it’s told from a narrow range of experts and institutions. // The Web is the ultimate marketplace of ideas, governed by the laws of big numbers. – Chris Anderson',
// 'No hay presente ni futuro / sólo el pasado que acontece una y otra vez / ahora. – Eugene O´Neill',
'¡Digan ustedes si no es lindo vagar! Hay quienes sienten la vagancia, no como el no hacer, sino como un placer físico, una alegría profunda... Y es que en todo vago, aun el más atorrante, hay una naturaleza contemplativa. – Roberto Arlt',
// 'By choosing the essential, we create great impact with minimal resources. Always choose the essential to maximize your time and energy. – Leo Babuta',
// 'Cuantos más hombres libres me rodeen y cuanto más amplia y profunda sea su libertad, tanto más profunda y amplia será la mía. // Cuanto más libres y desarrollados están el comercio y la industria, más completa es la desmoralización de los pocos privilegiados y mayores son, por otra parte, la miseria, los lamentos y el legítimo furor de las masas de trabajadores. – Mijail Aleksandrovich Bakunin',
'Creo en la locura, en la verdad de lo inexplicable, en el sentido común de las piedras, en la locura de las flores, en la enfermedad guardada para la humanidad por los astronautas del Apollo. // Creo en la imposibilidad de la existencia, en el humor de las montañas, en el absurdo del electromagnetismo, en la farsa de la geometría, en la crueldad de la aritmética, en las intenciones asesinas de la lógica. // Creo en la amabilidad del escalpelo del cirujano, en la geometría sin límites de la pantalla de cine, en el universo oculto dentro de los supermercados, en la soledad del sol, en la cháchara de los planetas, en lo repetitivo de nosotros mismos, en la inexistencia del universo y el aburrimiento del átomo. Creo en la no existencia del pasado, en la muerte del futuro, en las infinitas posibilidades del presente. // Creo en los diseñadores de las pirámides, del Empire State Building, del Fuehrerbunker de Berlín, en las pasarelas de Wake Island. // Creo en los próximos cinco minutos. // Creo en la historia de mis pies. // Creo en las migrañas, el aburrimiento de las tardes, el miedo a los calendarios, la traición de los relojes. // Creo en la ansiedad, la psicosis y la desesperación. // Creo en la muerte de las emociones y el triunfo de la imaginación. // Creo en el alcoholismo, las enfermedades venéreas, la fiebre y la fatiga. Creo en el dolor. Creo en los chicos. // Creo en los mapas, los diagramas, los códigos, los juegos de ajedrez, los acertijos, la tabla de horarios de las aerolíneas, los indicadores de los aeropuertos. Creo en todas las excusas. // Creo en todas las razones. // Creo en todas las alucinaciones. // Creo en el misterio y la melancolía de una mano, en la amabilidad de los árboles, en la sabiduría de la luz. –  J. G. Ballard', 
'Science and technology multiple around us. To an increasing extent they dictate the languages in which we speak and think. Either we use those languages, or we remain mute. –  J. G. Ballard',
]
function newQuote() {
var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}

