syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set spell
set spelllang=en,es
set clipboard=unnamedplus
set showcmd " https://stackoverflow.com/a/8160809/6253165
set encoding=utf-8
set fileencoding=utf-8
set nocompatible " no vi [from previous millenia]
set linebreak
set number
set relativenumber
set nobackup
set nowritebackup
set noswapfile
set nobackup
set shortmess+=A
set clipboard=unnamedplus
set omnifunc=htmlcomplete#CompleteTags
set ignorecase " case insensitive searching

nnoremap <silent> - s<c-r>=tr(@",'aeioucnAEIOUCNáéíóúçñÁÉÍÓÚÇÑ', 'áéíóúçñÁÉÍÓUÇÑaeioucnAEIOUCN')<cr><esc>

" https://github.com/tpope/vim-commentary // gcc +++++++
autocmd FileType apache setlocal commentstring=#\ %s

hi clear SpellBad
hi SpellBad cterm=bold cterm=underline  ctermfg=yellow " guifg=yellow 
:iabbrev </ </<C-X><C-O>
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
set wildmode=longest,list,full
set wildmenu

" http://vimcasts.org/blog/2013/02/habit-breaking-habit-making/
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" http://learnvimscriptthehardway.stevelosh.com/chapters/07.html
" this allows direct acces to vimrc from any vim instance
:nnoremap <leader>ev :vsplit $MYVIMRC<cr>
:nnoremap <leader>eb :vsplit /home/nilon/Public/ramoneando/docs/mybib.bib<cr>
:nnoremap <leader>ei :vsplit /home/nilon/Public/ramoneando/ultra/index.html<cr>

" jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

" Make calcurse use markdown by default
autocmd BufRead,BufNewFile /tmp/calcurse set filetype#markdown
autocmd BufRead,BufNewFile ~/.calcurse/notes/* set filetype#markdown

" saving with <C-S> instead of :w<R>
noremap <silent> <C-S>          :update<CR>
vnoremap <silent> <C-S>         <C-C>:update<CR>
inoremap <silent> <C-S>         <C-O>:update<CR>

" Word count | Get line, word and character counts with F2.
" https://www.dralexnorman.net/post/a-literate-vimrc-file/
map <F2> :!wc <C-R>%<CR>

" Open my .bib file | Open my bibliography file in split
" map <F9> :vsp<space>~/Public/ramoneando/docs/mybib.bib<CR>

" https://stackoverflow.com/questions/56052/best-way-to-insert-timestamp-in-vim " inserts date with F3
nmap <F3> i<C-R>=strftime("%Y-%m-%d")<CR><Esc>
imap <F3> <C-R>=strftime("%Y-%m-%d")<CR>

" incremental search " http://www.oualline.com/vim/10/top_10.html
:set incsearch

" How to fold/unfold HTML tags with Vim
" https://stackoverflow.com/a/17384809/6253165
" I use zO and zc to open and close nested folds, respectively.
" setlocal foldmethod=syntax
set foldmethod=indent
setlocal foldmethod=manual

" Go to last file if invoked without arguments.
autocmd VimEnter * nested if
  \ argc() == 0 &&
  \ bufname("%") == "" &&
  \ bufname("2" + 0) != "" |
  \   exe "normal! `0" |
  \ endif

" http://vim.wikia.com/wiki/Open_the_last_edited_file
" Open last active file(s) if VIM is invoked without arguments.
autocmd VimLeave * nested let buffernr = bufnr("$") |
    \ let buflist = [] |
    \ while buffernr > 0 |
    \	if buflisted(buffernr) |
    \	    let buflist += [ bufname(buffernr) ] |
    \	endif |
    \   let buffernr -= 1 |
    \ endwhile |
    \ if (!isdirectory($HOME . "/.vim")) |
    \	call mkdir($HOME . "/.vim") |
    \ endif |
    \ call writefile(reverse(buflist), $HOME . "/.vim/buflist.txt")

autocmd VimEnter * nested if argc() == 0 && filereadable($HOME . "/.vim/buflist.txt") |
    \	for line in readfile($HOME . "/.vim/buflist.txt") |
    \	    if filereadable(line) |
    \		execute "tabedit " . line |
    \		set bufhidden=delete |
    \	    endif |
    \	endfor |
    \	tabclose 1 |
    \ endif"
